env:
 - GHCVER=7.6.3
 - GHCVER=7.8.4

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install libnetcdf-dev libgsl0-dev liblapack-dev
 - travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER-prof ghc-$GHCVER-dyn happy
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$PATH

install:
 - cabal update
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi
 - cabal install c2hs
 - cabal install --only-dependencies --enable-tests

script:
 - cabal install && cabal configure --enable-tests && cabal build && cabal test
